version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "inventory-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cixq0vp7d4xn"
s3_prefix = "inventory-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
